{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "7bee5e9f-8aa1-4d0c-aa69-a0994b8b4a8f",
   "metadata": {},
   "source": [
    "# Q1: why we have to use the Exception class while creating a Custom Exception.\n",
    "+ Python has quite a few built-in exception classes for all occasions. For example, there’s ZeroDivisionError raised when you try to divide by zero. Or ValueError raised on many occasions – also when you try to convert a string to an integer that doesn’t look like one"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b150ced0-9d42-45f8-92ad-acb612ee269b",
   "metadata": {},
   "outputs": [],
   "source": [
    "1 / 0  # doomed to fail\n",
    "# Traceback (most recent call last):\n",
    "#  File \"<stdin>\", line 1, in <module>\n",
    "# ZeroDivisionError: division by zero\n",
    "\n",
    "int(\"Python\")  # can't do this\n",
    "# Traceback (most recent call last):\n",
    "#  File \"<stdin>\", line 1, in <module>\n",
    "# ValueError: invalid literal for int() with base 10: 'Python'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83c91e0d-e2eb-4de0-9bc5-d39b17841e24",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exceptions can be handled using try..except block\n",
    "from datetime import timedelta, date\n",
    "\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        year_of_birth = int(input(\"Enter your year of birth and I'll tell you how old are you!\"))\n",
    "    except ValueError as exc:\n",
    "        print(\"Invalid value! Try again.\")\n",
    "\n",
    "    break\n",
    "\n",
    "...  # rest ommitted, non-essential for the blog post"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cd71be5a-cc26-4770-88d6-31e3d3a6dac5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Creating a new exception is trivial – just subclass Exception class:\n",
    "class MyCustomError(Exception):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "516d4dba-a207-418c-9fe0-5ed2ca39387e",
   "metadata": {},
   "source": [
    "## Many libraries choose to allow you for precise error handling, e.g. requests or sqlalchemy. If you delve into the source code, you’ll see that their custom exceptions follow Python’s conventions. For instance, HTTPError from requests inherits from built-in IOError. Also, exceptions classes bundled with libraries follow naming schema by adding “Error” suffix. The bottom line is that without custom exceptions you would not be able to effectively do any error handling with 3rd party libraries. Built-in exceptions are already used in the standard library, so if you would try to handle IOError, you wouldn’t easily know if you are handling HTTP request failure or a problem with reading a file from a hard drive."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "cd0bc9e8-9249-4524-a84c-e1aa5395cddb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " BaseException\n",
      "... Exception\n",
      "...... TypeError\n",
      "......... FloatOperation\n",
      "......... MultipartConversionError\n",
      "...... StopAsyncIteration\n",
      "...... StopIteration\n",
      "...... ImportError\n",
      "......... ModuleNotFoundError\n",
      "......... ZipImportError\n",
      "...... OSError\n",
      "......... ConnectionError\n",
      "............ BrokenPipeError\n",
      "............ ConnectionAbortedError\n",
      "............ ConnectionRefusedError\n",
      "............ ConnectionResetError\n",
      "............... RemoteDisconnected\n",
      "......... BlockingIOError\n",
      "......... ChildProcessError\n",
      "......... FileExistsError\n",
      "......... FileNotFoundError\n",
      "......... IsADirectoryError\n",
      "......... NotADirectoryError\n",
      "......... InterruptedError\n",
      "............ InterruptedSystemCall\n",
      "......... PermissionError\n",
      "......... ProcessLookupError\n",
      "......... TimeoutError\n",
      "......... UnsupportedOperation\n",
      "......... itimer_error\n",
      "......... herror\n",
      "......... gaierror\n",
      "......... SSLError\n",
      "............ SSLCertVerificationError\n",
      "............ SSLZeroReturnError\n",
      "............ SSLWantWriteError\n",
      "............ SSLWantReadError\n",
      "............ SSLSyscallError\n",
      "............ SSLEOFError\n",
      "......... Error\n",
      "............ SameFileError\n",
      "......... SpecialFileError\n",
      "......... ExecError\n",
      "......... ReadError\n",
      "......... URLError\n",
      "............ HTTPError\n",
      "............ ContentTooShortError\n",
      "......... BadGzipFile\n",
      "...... EOFError\n",
      "......... IncompleteReadError\n",
      "...... RuntimeError\n",
      "......... RecursionError\n",
      "......... NotImplementedError\n",
      "............ ZMQVersionError\n",
      "............ StdinNotImplementedError\n",
      "......... _DeadlockError\n",
      "......... BrokenBarrierError\n",
      "......... BrokenExecutor\n",
      "............ BrokenThreadPool\n",
      "......... SendfileNotAvailableError\n",
      "......... ExtractionError\n",
      "......... VariableError\n",
      "...... NameError\n",
      "......... UnboundLocalError\n",
      "...... AttributeError\n",
      "......... FrozenInstanceError\n",
      "...... SyntaxError\n",
      "......... IndentationError\n",
      "............ TabError\n",
      "...... LookupError\n",
      "......... IndexError\n",
      "......... KeyError\n",
      "............ NoSuchKernel\n",
      "............ UnknownBackend\n",
      "......... CodecRegistryError\n",
      "...... ValueError\n",
      "......... UnicodeError\n",
      "............ UnicodeEncodeError\n",
      "............ UnicodeDecodeError\n",
      "............ UnicodeTranslateError\n",
      "......... UnsupportedOperation\n",
      "......... JSONDecodeError\n",
      "......... SSLCertVerificationError\n",
      "......... Error\n",
      "......... UnsupportedDigestmodError\n",
      "......... IllegalMonthError\n",
      "......... IllegalWeekdayError\n",
      "......... ParserError\n",
      "......... ClassNotFound\n",
      "......... ClipboardEmpty\n",
      "......... MessageDefect\n",
      "............ NoBoundaryInMultipartDefect\n",
      "............ StartBoundaryNotFoundDefect\n",
      "............ CloseBoundaryNotFoundDefect\n",
      "............ FirstHeaderLineIsContinuationDefect\n",
      "............ MisplacedEnvelopeHeaderDefect\n",
      "............ MissingHeaderBodySeparatorDefect\n",
      "............ MultipartInvariantViolationDefect\n",
      "............ InvalidMultipartContentTransferEncodingDefect\n",
      "............ UndecodableBytesDefect\n",
      "............ InvalidBase64PaddingDefect\n",
      "............ InvalidBase64CharactersDefect\n",
      "............ InvalidBase64LengthDefect\n",
      "............ HeaderDefect\n",
      "............... InvalidHeaderDefect\n",
      "............... HeaderMissingRequiredValue\n",
      "............... NonPrintableDefect\n",
      "............... ObsoleteHeaderDefect\n",
      "............... NonASCIILocalPartDefect\n",
      "............... InvalidDateDefect\n",
      "......... MacroToEdit\n",
      "......... InvalidFileException\n",
      "......... UnequalIterablesError\n",
      "......... InvalidVersion\n",
      "......... _InvalidELFFileHeader\n",
      "......... InvalidWheelFilename\n",
      "......... InvalidSdistFilename\n",
      "......... InvalidSpecifier\n",
      "......... InvalidMarker\n",
      "......... UndefinedComparison\n",
      "......... UndefinedEnvironmentName\n",
      "......... InvalidRequirement\n",
      "............ RequirementParseError\n",
      "......... InvalidVersion\n",
      "...... AssertionError\n",
      "...... ArithmeticError\n",
      "......... FloatingPointError\n",
      "......... OverflowError\n",
      "......... ZeroDivisionError\n",
      "............ DivisionByZero\n",
      "............ DivisionUndefined\n",
      "......... DecimalException\n",
      "............ Clamped\n",
      "............ Rounded\n",
      "............... Underflow\n",
      "............... Overflow\n",
      "............ Inexact\n",
      "............... Underflow\n",
      "............... Overflow\n",
      "............ Subnormal\n",
      "............... Underflow\n",
      "............ DivisionByZero\n",
      "............ FloatOperation\n",
      "............ InvalidOperation\n",
      "............... ConversionSyntax\n",
      "............... DivisionImpossible\n",
      "............... DivisionUndefined\n",
      "............... InvalidContext\n",
      "...... SystemError\n",
      "......... CodecRegistryError\n",
      "...... ReferenceError\n",
      "...... MemoryError\n",
      "...... BufferError\n",
      "...... Warning\n",
      "......... UserWarning\n",
      "............ GetPassWarning\n",
      "............ FormatterWarning\n",
      "......... EncodingWarning\n",
      "......... DeprecationWarning\n",
      "............ ProvisionalWarning\n",
      "......... PendingDeprecationWarning\n",
      "......... SyntaxWarning\n",
      "......... RuntimeWarning\n",
      "............ ProactorSelectorThreadWarning\n",
      "............ UnknownTimezoneWarning\n",
      "............ PEP440Warning\n",
      "......... FutureWarning\n",
      "............ ProvisionalCompleterWarning\n",
      "......... ImportWarning\n",
      "......... UnicodeWarning\n",
      "......... BytesWarning\n",
      "......... ResourceWarning\n",
      "......... DeprecatedTzFormatWarning\n",
      "......... PkgResourcesDeprecationWarning\n",
      "...... _OptionError\n",
      "...... _Error\n",
      "...... error\n",
      "...... Verbose\n",
      "...... Error\n",
      "...... SubprocessError\n",
      "......... CalledProcessError\n",
      "......... TimeoutExpired\n",
      "...... TokenError\n",
      "...... StopTokenizing\n",
      "...... ClassFoundException\n",
      "...... EndOfBlock\n",
      "...... TraitError\n",
      "...... Error\n",
      "...... Error\n",
      "......... CancelledError\n",
      "......... TimeoutError\n",
      "......... InvalidStateError\n",
      "...... _GiveupOnSendfile\n",
      "...... error\n",
      "...... Incomplete\n",
      "...... TimeoutError\n",
      "...... InvalidStateError\n",
      "...... LimitOverrunError\n",
      "...... QueueEmpty\n",
      "...... QueueFull\n",
      "...... Empty\n",
      "...... Full\n",
      "...... ArgumentError\n",
      "...... ZMQBaseError\n",
      "......... ZMQError\n",
      "............ ContextTerminated\n",
      "............ Again\n",
      "............ InterruptedSystemCall\n",
      "......... ZMQBindError\n",
      "......... NotDone\n",
      "...... PickleError\n",
      "......... PicklingError\n",
      "......... UnpicklingError\n",
      "...... _Stop\n",
      "...... ArgumentError\n",
      "...... ArgumentTypeError\n",
      "...... ConfigError\n",
      "......... ConfigLoaderError\n",
      "............ ArgumentError\n",
      "......... ConfigFileNotFound\n",
      "...... ConfigurableError\n",
      "......... MultipleInstanceError\n",
      "...... ApplicationError\n",
      "...... error\n",
      "...... TimeoutError\n",
      "...... error\n",
      "...... ReturnValueIgnoredError\n",
      "...... KeyReuseError\n",
      "...... UnknownKeyError\n",
      "...... LeakedCallbackError\n",
      "...... BadYieldError\n",
      "...... ReturnValueIgnoredError\n",
      "...... Return\n",
      "...... InvalidPortNumber\n",
      "...... error\n",
      "...... LZMAError\n",
      "...... RegistryError\n",
      "...... _GiveupOnFastCopy\n",
      "...... Error\n",
      "......... NoSectionError\n",
      "......... DuplicateSectionError\n",
      "......... DuplicateOptionError\n",
      "......... NoOptionError\n",
      "......... InterpolationError\n",
      "............ InterpolationMissingOptionError\n",
      "............ InterpolationSyntaxError\n",
      "............ InterpolationDepthError\n",
      "......... ParsingError\n",
      "............ MissingSectionHeaderError\n",
      "...... NoIPAddresses\n",
      "...... BadZipFile\n",
      "...... LargeZipFile\n",
      "...... BadEntryPoint\n",
      "...... NoSuchEntryPoint\n",
      "...... DuplicateKernelError\n",
      "...... ErrorDuringImport\n",
      "...... NotOneValueFound\n",
      "...... CannotEval\n",
      "...... OptionError\n",
      "...... BdbQuit\n",
      "...... Restart\n",
      "...... ExceptionPexpect\n",
      "......... EOF\n",
      "......... TIMEOUT\n",
      "...... PtyProcessError\n",
      "...... FindCmdError\n",
      "...... HomeDirError\n",
      "...... ProfileDirError\n",
      "...... IPythonCoreError\n",
      "......... TryNext\n",
      "......... UsageError\n",
      "......... StdinNotImplementedError\n",
      "...... InputRejected\n",
      "...... GetoptError\n",
      "...... ErrorToken\n",
      "...... PrefilterError\n",
      "...... AliasError\n",
      "......... InvalidAliasError\n",
      "...... Error\n",
      "......... InterfaceError\n",
      "......... DatabaseError\n",
      "............ InternalError\n",
      "............ OperationalError\n",
      "............ ProgrammingError\n",
      "............ IntegrityError\n",
      "............ DataError\n",
      "............ NotSupportedError\n",
      "...... Warning\n",
      "...... SpaceInInput\n",
      "...... DOMException\n",
      "......... IndexSizeErr\n",
      "......... DomstringSizeErr\n",
      "......... HierarchyRequestErr\n",
      "......... WrongDocumentErr\n",
      "......... InvalidCharacterErr\n",
      "......... NoDataAllowedErr\n",
      "......... NoModificationAllowedErr\n",
      "......... NotFoundErr\n",
      "......... NotSupportedErr\n",
      "......... InuseAttributeErr\n",
      "......... InvalidStateErr\n",
      "......... SyntaxErr\n",
      "......... InvalidModificationErr\n",
      "......... NamespaceErr\n",
      "......... InvalidAccessErr\n",
      "......... ValidationErr\n",
      "...... ValidationError\n",
      "...... EditReadOnlyBuffer\n",
      "...... _Retry\n",
      "...... InvalidLayoutError\n",
      "...... HeightIsUnknownError\n",
      "...... ParserSyntaxError\n",
      "...... InternalParseError\n",
      "...... _PositionUpdatingFinished\n",
      "...... SimpleGetItemNotFound\n",
      "...... UncaughtAttributeError\n",
      "...... HasNoContext\n",
      "...... ParamIssue\n",
      "...... _JediError\n",
      "......... InternalError\n",
      "......... WrongVersion\n",
      "......... RefactoringError\n",
      "...... OnErrorLeaf\n",
      "...... InvalidPythonEnvironment\n",
      "...... MessageError\n",
      "......... MessageParseError\n",
      "............ HeaderParseError\n",
      "............ BoundaryError\n",
      "......... MultipartConversionError\n",
      "......... CharsetError\n",
      "...... Error\n",
      "...... HTTPException\n",
      "......... NotConnected\n",
      "......... InvalidURL\n",
      "......... UnknownProtocol\n",
      "......... UnknownTransferEncoding\n",
      "......... UnimplementedFileMode\n",
      "......... IncompleteRead\n",
      "......... ImproperConnectionState\n",
      "............ CannotSendRequest\n",
      "............ CannotSendHeader\n",
      "............ ResponseNotReady\n",
      "......... BadStatusLine\n",
      "............ RemoteDisconnected\n",
      "......... LineTooLong\n",
      "...... InteractivelyDefined\n",
      "...... KillEmbedded\n",
      "...... Error\n",
      "......... NoSuchProcess\n",
      "............ ZombieProcess\n",
      "......... AccessDenied\n",
      "......... TimeoutExpired\n",
      "...... _Ipv6UnsupportedError\n",
      "...... QueueEmpty\n",
      "...... QueueFull\n",
      "...... DebuggerInitializationError\n",
      "...... ExpatError\n",
      "...... Error\n",
      "......... ProtocolError\n",
      "......... ResponseError\n",
      "......... Fault\n",
      "...... ParseBaseException\n",
      "......... ParseException\n",
      "......... ParseFatalException\n",
      "............ ParseSyntaxException\n",
      "...... RecursiveGrammarException\n",
      "...... ResolutionError\n",
      "......... VersionConflict\n",
      "............ ContextualVersionConflict\n",
      "......... DistributionNotFound\n",
      "......... UnknownExtra\n",
      "...... _Error\n",
      "...... UnableToResolveVariableException\n",
      "...... InvalidTypeInArgsException\n",
      "... GeneratorExit\n",
      "... SystemExit\n",
      "... KeyboardInterrupt\n",
      "... CancelledError\n",
      "... AbortThread\n"
     ]
    }
   ],
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy.\n",
    "def classtree(cls, indent=0):\n",
    "    print('.' * indent, cls.__name__)\n",
    "    for subcls in cls.__subclasses__():\n",
    "        classtree(subcls, indent + 3)\n",
    "\n",
    "classtree(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c39d72d7-1c81-4a52-8dfb-2bd097f7d24d",
   "metadata": {},
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "ArithmeticError is thrown when an error occurs while performing mathematical operations. These errors include attempting to perform a bitshift by a negative amount, and any call to intdiv() that would result in a value outside the possible bounds of an int."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bcca6bf7-9e39-4f7c-8aab-682788c37591",
   "metadata": {},
   "source": [
    "# Q3: What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "# The 'ArithmeticError' class is a base class for all errors that occur during arithmetic operations, such as division by zero or numeric overflow. Some of the errors that are defined in the 'ArithmeticError' class are"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3d7072b3-ee9b-4cd6-8adc-acd4c9df1ec2",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 4\u001b[0m\n\u001b[1;32m      2\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m10\u001b[39m\n\u001b[1;32m      3\u001b[0m y \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[0;32m----> 4\u001b[0m z \u001b[38;5;241m=\u001b[39m \u001b[43mx\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43m \u001b[49m\u001b[43my\u001b[49m  \u001b[38;5;66;03m# raises ZeroDivisionError\u001b[39;00m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# 1. ZeroDivisionError: This error is raised when you try to divide a number by zero. For example:\n",
    "x = 10\n",
    "y = 0\n",
    "z = x / y  # raises ZeroDivisionError\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a70d23d1-6b09-4a62-b36e-8adc37fd0432",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'try' statement on line 2 (3141160728.py, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[10], line 4\u001b[0;36m\u001b[0m\n\u001b[0;31m    except ArithmeticError as e:\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m expected an indented block after 'try' statement on line 2\n"
     ]
    }
   ],
   "source": [
    "# 2.  'OverflowError': This error is raised when a calculation exceeds the maximum representable value for a numeric type. For example:\n",
    "try:\n",
    "    # some arithmetic operation\n",
    "except ArithmeticError as e:\n",
    "    print(\"Arithmetic error occurred:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5dae6e95-22b0-440c-a77f-73a25244cec4",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'try' statement on line 2 (1567821688.py, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[11], line 4\u001b[0;36m\u001b[0m\n\u001b[0;31m    except ArithmeticError as e:\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m expected an indented block after 'try' statement on line 2\n"
     ]
    }
   ],
   "source": [
    "# 'ZeroDivisionError'  and 'OverflowError'.\n",
    "try:\n",
    "    # some arithmetic operation\n",
    "except ArithmeticError as e:\n",
    "    print(\"Arithmetic error occurred:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "86df8a28-ed69-44c3-a678-58a289323521",
   "metadata": {},
   "source": [
    "# Q4:  The 'LookupError' class is a base class for all errors that occur when you try to access an invalid index or key in a sequence or mapping object. Some of the errors that are defined in the 'LookupError' class are:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "950331ac-7fdd-4351-aa49-ea4c2f82ec95",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'d'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[12], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# 1. 'KeyError': This error is raised when you try to access a key that does not exist in a dictionary. For example:\u001b[39;00m\n\u001b[1;32m      2\u001b[0m my_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mc\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m----> 3\u001b[0m value \u001b[38;5;241m=\u001b[39m \u001b[43mmy_dict\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43md\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m  \u001b[38;5;66;03m# raises KeyError\u001b[39;00m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'd'"
     ]
    }
   ],
   "source": [
    "# 1. 'KeyError': This error is raised when you try to access a key that does not exist in a dictionary. For example:\n",
    "\n",
    "my_dict = {\"a\": 1, \"b\": 2, \"c\": 3}\n",
    "value = my_dict[\"d\"]  # raises KeyError\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f394355f-9673-4142-9992-b6f154777e4c",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# 2. 'IndexError': This error is raised when you try to access an index that is out of range in a list or other sequence object. For example:\u001b[39;00m\n\u001b[1;32m      2\u001b[0m my_list \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m]\n\u001b[0;32m----> 3\u001b[0m value \u001b[38;5;241m=\u001b[39m \u001b[43mmy_list\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m]\u001b[49m  \u001b[38;5;66;03m# raises IndexError\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m# In this case, Python raises an IndexError because we're trying to access the index 3, which is out of range for the my_list list (the maximum index is 2).\u001b[39;00m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "# 2. 'IndexError': This error is raised when you try to access an index that is out of range in a list or other sequence object. For example:\n",
    "my_list = [1, 2, 3]\n",
    "value = my_list[3]  # raises IndexError\n",
    "# In this case, Python raises an IndexError because we're trying to access the index '3', which is out of range for the my_list list (the maximum index is '2')."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b7ed2e14-96b7-48b7-b8f6-39454febdfd3",
   "metadata": {},
   "source": [
    "# Both of these errors are subclasses of 'LookupError', which is a general class for lookup errors. This means that you can catch either of these errors using a try-except block that catches 'LookupError':"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "2da9f9b6-27ba-40bd-9651-b2fd050b3b4c",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'try' statement on line 2 (623626762.py, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[14], line 4\u001b[0;36m\u001b[0m\n\u001b[0;31m    except LookupError as e:\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m expected an indented block after 'try' statement on line 2\n"
     ]
    }
   ],
   "source": [
    "# subclasses of 'LookupError'\n",
    "try:\n",
    "    # some lookup operation\n",
    "except LookupError as e:\n",
    "    print(\"Lookup error occurred:\", e)\n",
    "    \n",
    "# This will catch any lookup error that occurs during the operation, including 'KeyError' and 'IndexError'."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d902515c-80f8-493a-a0b4-5fad41789457",
   "metadata": {},
   "source": [
    "# Q5: 'ImportError' is an exception that is raised when you try to import a module or a symbol from a module that cannot be found, or when there is an error during the import process. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "8b8b27ef-f598-40d0-a1ae-b4c46e9f3f2b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Import error occurred: No module named 'some_module'\n"
     ]
    }
   ],
   "source": [
    "# Example:\n",
    "try:\n",
    "    import some_module  # raises ImportError\n",
    "except ImportError as e:\n",
    "    print(\"Import error occurred:\", e)\n",
    "    \n",
    "# In this case, if the some_module module cannot be found, Python will raise an 'ImportError' exception. You can catch this exception using a try-except block, as shown above."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b01f083e-e516-4e07-8393-c50b95481e81",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Module not found error occurred: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "# ModuleNotFoundError: raised when you try to import a module that does not exist\n",
    "try:\n",
    "    import non_existent_module  # raises ModuleNotFoundError\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"Module not found error occurred:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d2db5f5a-e4fd-442c-b390-eb1ed282e9a3",
   "metadata": {},
   "source": [
    "# Q6: List down some best practices for exception handling in python\n",
    "\n",
    "1. Catch only the exceptions you expect: It's good practice to catch only the specific exceptions that you're expecting to occur in your code. This helps to avoid catching unexpected exceptions that could hide bugs in your code.\n",
    "\n",
    "2. se specific exception classes: Use specific exception classes instead of catching general exceptions like 'Exception' or 'BaseException'. This makes your code more readable and easier to debug.\n",
    "\n",
    "3. Use try-except-finally blocks: Use try-except-finally blocks to handle exceptions and cleanup resources. The 'finally' block is executed regardless of whether an exception occurred or not, so it's a good place to release any resources that were acquired in the 'try' block.\n",
    "\n",
    "4. Don't use bare except clauses: Avoid using bare except clauses ('except:') as they catch all exceptions, including system exceptions like 'KeyboardInterrupt' and 'SystemExit'. Instead, use specific exception classes or a tuple of exceptions that you want to catch.\n",
    "\n",
    "5. Use the logging module: Use the 'logging' module to log exceptions and other errors in your code. This makes it easier to debug your code and provides a record of errors that occur during runtime.\n",
    "\n",
    "6. Raise exceptions when appropriate: Raise exceptions when appropriate to indicate errors or unexpected conditions in your code. This helps to make your code more robust and easier to maintain.\n",
    "\n",
    "7. Use context managers: Use context managers ('with' statements) to manage resources like files and network connections. Context managers ensure that resources are released properly even if an exception occurs.\n",
    "\n",
    "8. Document your exceptions: Document the exceptions that your code raises and catches. This makes it easier for other developers to understand how your code works and how to use it properly."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ebf68df7-22e6-48a5-a4f8-83b6e9e5cf7d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
